[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "MonacoB"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Monaco"
style = "Italic"

[font.normal]
family = "Monaco Nerd Font"
style = "Regular"

[window.dimensions]
columns = 90
lines = 28

[keyboard]
bindings = [
   { key = "Return", mods = "Control", action = "SpawnNewInstance" }
]
# BEGIN WAL
[colors.primary]
background = '#191a19'
foreground = '#c5c5c5'

[colors.cursor]
text   = '#191a19' # Apply background color to color of text inside cursor
cursor = '#c5c5c5' # Apply foreground color to color of cursor

[colors.vi_mode_cursor]
text    = '#191a19' # Same as above
cursor  = '#c5c5c5'

[colors.search.matches]
foreground = '#191a19' # Same as above
background = '#c5c5c5' # Apply bright/white color to bg color of matching search

[colors.search.focused_match]
foreground = 'CellBackground'
background = 'CellForeground'

[colors.line_indicator]
foreground = 'None'
background = 'None'

[colors.footer_bar]
foreground = '#525352'
background = '#c5c5c5'

[colors.selection]
text       = 'CellBackground'
background = 'CellForeground'

[colors.normal]
black   = '#191a19'
red     = '#805274'
green   = '#8f8692'
yellow  = '#a09bb8'
blue    = '#c29998'
magenta = '#baa8bb'
cyan    = '#d1c793'
white   = '#c5c5c5'

[colors.bright]
black   = '#525352'
red     = '#805274'
green   = '#8f8692'
yellow  = '#a09bb8'
blue    = '#c29998'
magenta = '#baa8bb'
cyan    = '#d1c793'
white   = '#c5c5c5'
# END WAL
