[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "MonacoB"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Monaco"
style = "Italic"

[font.normal]
family = "Monaco Nerd Font"
style = "Regular"

[window.dimensions]
columns = 90
lines = 28

[keyboard]
bindings = [
   { key = "Return", mods = "Control", action = "SpawnNewInstance" }
]
# BEGIN WAL
[colors.primary]
background = '#161618'
foreground = '#c4c4c5'

[colors.cursor]
text   = '#161618' # Apply background color to color of text inside cursor
cursor = '#c4c4c5' # Apply foreground color to color of cursor

[colors.vi_mode_cursor]
text    = '#161618' # Same as above
cursor  = '#c4c4c5'

[colors.search.matches]
foreground = '#161618' # Same as above
background = '#c4c4c5' # Apply bright/white color to bg color of matching search

[colors.search.focused_match]
foreground = 'CellBackground'
background = 'CellForeground'

[colors.line_indicator]
foreground = 'None'
background = 'None'

[colors.footer_bar]
foreground = '#505051'
background = '#c4c4c5'

[colors.selection]
text       = 'CellBackground'
background = 'CellForeground'

[colors.normal]
black   = '#161618'
red     = '#314283'
green   = '#475d9e'
yellow  = '#4968ba'
blue    = '#6a7197'
magenta = '#6d8ace'
cyan    = '#95b5f0'
white   = '#c4c4c5'

[colors.bright]
black   = '#505051'
red     = '#314283'
green   = '#475d9e'
yellow  = '#4968ba'
blue    = '#6a7197'
magenta = '#6d8ace'
cyan    = '#95b5f0'
white   = '#c4c4c5'
# END WAL
