[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "MonacoB"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Monaco"
style = "Italic"

[font.normal]
family = "Monaco Nerd Font"
style = "Regular"

[window.dimensions]
columns = 90
lines = 28

[keyboard]
bindings = [
   { key = "Return", mods = "Control", action = "SpawnNewInstance" }
]
# BEGIN WAL
[colors.primary]
background = '#151819'
foreground = '#c4c5c5'

[colors.cursor]
text   = '#151819' # Apply background color to color of text inside cursor
cursor = '#c4c5c5' # Apply foreground color to color of cursor

[colors.vi_mode_cursor]
text    = '#151819' # Same as above
cursor  = '#c4c5c5'

[colors.search.matches]
foreground = '#151819' # Same as above
background = '#c4c5c5' # Apply bright/white color to bg color of matching search

[colors.search.focused_match]
foreground = 'CellBackground'
background = 'CellForeground'

[colors.line_indicator]
foreground = 'None'
background = 'None'

[colors.footer_bar]
foreground = '#4f5152'
background = '#c4c5c5'

[colors.selection]
text       = 'CellBackground'
background = 'CellForeground'

[colors.normal]
black   = '#151819'
red     = '#1a4e59'
green   = '#2d7e84'
yellow  = '#64928d'
blue    = '#3ca6ac'
magenta = '#48afb1'
cyan    = '#77c5c0'
white   = '#c4c5c5'

[colors.bright]
black   = '#4f5152'
red     = '#1a4e59'
green   = '#2d7e84'
yellow  = '#64928d'
blue    = '#3ca6ac'
magenta = '#48afb1'
cyan    = '#77c5c0'
white   = '#c4c5c5'
# END WAL
