[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "MonacoB"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Monaco"
style = "Italic"

[font.normal]
family = "Monaco Nerd Font"
style = "Regular"

[window.dimensions]
columns = 90
lines = 28

[keyboard]
bindings = [
   { key = "Return", mods = "Control", action = "SpawnNewInstance" }
]
# BEGIN WAL
[colors.primary]
background = '#281c1e'
foreground = '#c9c6c6'

[colors.cursor]
text   = '#281c1e' # Apply background color to color of text inside cursor
cursor = '#c9c6c6' # Apply foreground color to color of cursor

[colors.vi_mode_cursor]
text    = '#281c1e' # Same as above
cursor  = '#c9c6c6'

[colors.search.matches]
foreground = '#281c1e' # Same as above
background = '#c9c6c6' # Apply bright/white color to bg color of matching search

[colors.search.focused_match]
foreground = 'CellBackground'
background = 'CellForeground'

[colors.line_indicator]
foreground = 'None'
background = 'None'

[colors.footer_bar]
foreground = '#5d5456'
background = '#c9c6c6'

[colors.selection]
text       = 'CellBackground'
background = 'CellForeground'

[colors.normal]
black   = '#281c1e'
red     = '#e24f61'
green   = '#c28289'
yellow  = '#ed8e95'
blue    = '#e6a8c1'
magenta = '#bdd3dc'
cyan    = '#f2d4a9'
white   = '#c9c6c6'

[colors.bright]
black   = '#5d5456'
red     = '#e24f61'
green   = '#c28289'
yellow  = '#ed8e95'
blue    = '#e6a8c1'
magenta = '#bdd3dc'
cyan    = '#f2d4a9'
white   = '#c9c6c6'
# END WAL
