[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "MonacoB"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Monaco"
style = "Italic"

[font.normal]
family = "Monaco Nerd Font"
style = "Regular"

[window.dimensions]
columns = 90
lines = 28

[keyboard]
bindings = [
   { key = "Return", mods = "Control", action = "SpawnNewInstance" }
]
# BEGIN WAL
[colors.primary]
background = '#1d1d1c'
foreground = '#c6c6c6'

[colors.cursor]
text   = '#1d1d1c' # Apply background color to color of text inside cursor
cursor = '#c6c6c6' # Apply foreground color to color of cursor

[colors.vi_mode_cursor]
text    = '#1d1d1c' # Same as above
cursor  = '#c6c6c6'

[colors.search.matches]
foreground = '#1d1d1c' # Same as above
background = '#c6c6c6' # Apply bright/white color to bg color of matching search

[colors.search.focused_match]
foreground = 'CellBackground'
background = 'CellForeground'

[colors.line_indicator]
foreground = 'None'
background = 'None'

[colors.footer_bar]
foreground = '#555554'
background = '#c6c6c6'

[colors.selection]
text       = 'CellBackground'
background = 'CellForeground'

[colors.normal]
black   = '#1d1d1c'
red     = '#786161'
green   = '#836874'
yellow  = '#918c8e'
blue    = '#bea2a6'
magenta = '#c6b0bf'
cyan    = '#afc1d2'
white   = '#c6c6c6'

[colors.bright]
black   = '#555554'
red     = '#786161'
green   = '#836874'
yellow  = '#918c8e'
blue    = '#bea2a6'
magenta = '#c6b0bf'
cyan    = '#afc1d2'
white   = '#c6c6c6'
# END WAL
