#! /bin/sh

MASTER_MONITER="DP-2"
SECOND_MONITER="HDMI-0"

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor ${MASTER_MONITER} -d 1 2 3 4 5 6 10
bspc monitor ${SECOND_MONITER} -d 7 8 9

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config top_padding 50
bspc config border_width 2
bspc config focused_border_color "#00ff00"
bspc config window_gap 15

bspc config split_ratio 0.55
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config external_rules_command $HOME/.config/bspwm/external_rules

bspc config -m ${SECOND_MONITER} top_padding 0
bspc config -m ${SECOND_MONITER} split_ratio 0.5

bspc rule -a "floatingTerminal" state=floating
bspc rule -a "scratchpad" state=floating sticky=true
bspc rule -a "statusutil" desktop=7 monitor=${SECOND_MONITER} state=titled
bspc rule -a "cavautil" desktop=7 monitor=${SECOND_MONITER} state=titled

# autostart
pgrep -x btop >/dev/null || alacritty -o "font.size=16" -t statusutil --class statusutil -e btop &
pgrep -x cava >/dev/null || alacritty -o "font.size=16" -t cava --class cavautil -e cava &
pgrep -x xfce4-power-manager >/dev/null || xfce4-power-manager &
pgrep -x xautolock >/dev/null || xautolock -time 30 -locker "~/dwm/dwm/i3lock/lock.sh" &
pgrep -x fcitx5 >/dev/null || fcitx5 &
pgrep -x redshift >/dev/null || redshift &
pgrep -x dunst >/dev/null || dunst &
pgrep -x picom >/dev/null || picom --animations &
pgrep -x polybar >/dev/null || $HOME/.config/bspwm/polybar/launch.sh &

for file in ~/.config/autostart/*.sh; do
  "$file" # execute
done
