#! /bin/sh

. "$HOME/.cache/wal/colors.sh"

MASTER_MONITER="DP-2"
SECOND_MONITER="HDMI-0"

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor ${MASTER_MONITER} -d $TOFWEOD_PRIMARY_DESKTOPS
bspc monitor ${SECOND_MONITER} -d $TOFWEOD_SIDE_DESKTOPS

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config top_padding 50
bspc config border_width 3
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
bspc config window_gap 15

bspc config split_ratio 0.55
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc config -m ${SECOND_MONITER} top_padding 0
bspc config -m ${SECOND_MONITER} split_ratio 0.5

bspc rule -a "floatingTerminal" state=floating
bspc rule -a "scratchpad" state=floating sticky=true
bspc rule -a "statusutil" desktop=$TOFWEOD_MONITOR_DESKTOP monitor=${SECOND_MONITER} state=titled
bspc rule -a "cavautil" desktop=$TOFWEOD_MONITOR_DESKTOP monitor=${SECOND_MONITER} state=titled
bspc rule -a "QQ" state=floating center=on
bspc rule -a "OSD Lyrics" manage=off
bspc rule -a "copyq" state=floating center=on
bspc rule -a 'org.mozilla.Thunderbird' desktop=$TOFWEOD_MAIL_DESKTOP
bspc rule -a 'steam' desktop=1
bspc rule -a 'SPlayer' desktop=$TOFWEOD_MUSIC_PLAYER_DESKTOP
bspc config external_rules_command $HOME/.config/bspwm/external_rules

# autostart
(pgrep -x cava >/dev/null || alacritty -o "font.size=8" -t cava --class cavautil -e cava &) &&
  (pgrep -x btop >/dev/null || alacritty -o "font.size=16" -t statusutil --class statusutil -e btop &)
pgrep -x xfce4-power-manager >/dev/null || xfce4-power-manager &
pgrep -x xautolock >/dev/null || xautolock -time 30 -locker "lock" &
pgrep -x fcitx5 >/dev/null || fcitx5 &
# use crontab to start at night
# pgrep -x redshift >/dev/null || redshift &
pgrep -x dunst >/dev/null || dunst &
pgrep -x picom >/dev/null || picom --animations &
pgrep -x polybar >/dev/null || $HOME/.config/bspwm/polybar/launch.sh &
pgrep -x copyq >/dev/null || copyq &
pgrep -x birdtray >/dev/null || birdtray &

for file in ~/.config/autostart/*.sh; do
  "$file" # execute
done
