#! /bin/sh

wid=$1
class=$2
instance=$3
consequences=$4

if [ "$instance" = fontforge ]; then
  title=$(xtitle "$wid")
  case "$title" in
  Layers | Tools | Warning)
    echo "focus=off"
    ;;
  esac
fi

case "$class" in
Lutris | Liferea)
  eval "$consequences"
  [ "$state" ] || echo "state=pseudo_tiled"
  ;;
Brave-browser)
  eval "$consequences"
  if [ $(xprop -id $wid WM_WINDOW_ROLE | cut -d= -f2 | sed -E 's/.*"(.*)".*/\1/') == "pop-up" ]; then
    echo "state=floating"
    echo "center=on"
    echo "rectangle=1000x600+0+0"
  fi
  ;;
"OSD Lyrics")
  includes=("Preferences" "Search lyrics" "Choose LRC file to assign" "About OSD Lyrics" "Credits" "License" "Select a folder")
  wmname=$(xprop -id $wid WM_NAME | cut -d= -f2 | sed -E 's/.*"(.*)".*/\1/')
  for item in "${includes[@]}"; do
    if [ "$wmname" == "$item" ]; then
      echo "manage=on"
      break
    fi
  done
  # if [ "$wmname" == "Preferences" ]; then
  #   echo "manage=on"
  # fi
  ;;
steam)
  eval "$consequences"
  wmname="$(xprop -id $wid WM_NAME | cut -d= -f2 | sed -E 's/.*"(.*)".*/\1/')"
  if [ "$wmname" == "Friends List" ]; then
    echo "state=floating"
    echo "center=on"
    echo "rectangle=500x900+0+50"
  fi
  if [ "$wmname" == "Steam Settings" ]; then
    echo "state=floating"
    echo "center=on"
  fi
  ;;
steam_app_4009635487)
  eval "$consequences"
  echo "desktop=$TOFWEOD_GAME_DESKTOP"
  if [ "$(xprop -id $wid WM_NAME | rg  '鸣潮')"  ]; then
    echo "state=floating"
	  echo "border=off"
    echo "locked=on"
    # echo "rectangle=2560x1440+0+0"
  fi
  ;;
steam_app_*)
  eval "$consequences"
  echo "desktop=$TOFWEOD_GAME_DESKTOP"
  echo "state=fullscreen"
  ;;
SPlayer)
  eval "$consequences"
  if [ "$(xprop -id $wid WM_NAME | cut -d= -f2 | rg '桌面歌词')" ]; then
    echo "manage=off"
  fi
  ;;
esac

# echo -e "One group: \n \
#     window ID : ${wid},\n \
#     title : $(xtitle "${wid}"),\n \
#     class name : ${class},\n \
#     instance name : ${instance},\n \
#     intermediate consequences : ${consequences}\n\n" \
#   >>~/log
